
service: graphql-api

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  memorySize: 5000

functions:
  graphql:
    handler: src/lambda.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true

plugins:
  - serverless-offline

package:
  exclude:
    - .gitignore
    - .editorconfig
    - .eslintrc.js
    - README.md
    - .git/**
    - .vscode/**
    - .serverless/**
    - tests
 