type Player {
    name: String!
    position: Position!
    champion: String!
    gold: Int!
    level: Int!
    kills: Int!
    deaths: Int!
    assists: Int!
    farm: Int!
    currentHealth: Int!
    maxHealth: Int!
    items: [Item]!
}

enum Position {
    TOP
    JUNGLE
    MID
    BOTTOM
    SUPPORT
}
